version: '3.8'
services:
  api:
    image: buwon-back
    container_name: simulator-back-end
    env_file: .production.env
    volumes:
      - /usr/syno/etc/certificate/_archive/g9eO0b:/app/certs:ro
    networks:
      - mysqlnet
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    restart: unless-stopped

networks:
  mysqlnet:
    external: true
    name: mysql-930_default
